[global]
load_dotenv = true
strict_env = false
disable_stdin = true
warn_timeout = "60s"
log_format = ""
bash_path = "/bin/bash"
hide_env_diff = true
disable_makefile = false

[whitelist]
prefix = ["/home/dev", "/ede/orgs"]
