name: Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "30 0 * * 0" # Rebuild Weekly, 00:30am picked arbitrarily

jobs:
  base: # This tier builds any os-specific containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: alpine
            version_tag: "3.17"
            dockerfile: 0-alpine/3.17/Dockerfile
            context: 0-alpine/3.17
          - name: debian
            version_tag: bullseye
            dockerfile: 0-debian/bullseye/Dockerfile
            context: 0-debian/bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}
            naxgrp.jfrog.io/nax-platform-docker/${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}
          tags: |
            type=raw,value=${{ matrix.version_tag }}-{{date 'YYYYMMDD'}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ matrix.version_tag }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix=${{ matrix.version_tag }}-
            type=sha,prefix=${{ matrix.version_tag }}-,format=long
            type=schedule,pattern=${{ matrix.version_tag }}-{{date 'YYYYMMDD'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_RW }}
      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: naxgrp.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          build-args: |
            CACHE_BUST=${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.version_tag }}-buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.version_tag }}-buildcache,mode=max
      - name: Record Summary
        run: |
          echo "### Docker Tags" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
  lang:
    needs:
      - base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: amazoncorretto
            version_tag: 17-alpine3.17
            dockerfile: 1-amazoncorretto/alpine3.17/Dockerfile
            context: 1-amazoncorretto/alpine3.17
            version_arg: "17"
          - name: amazoncorretto
            version_tag: 19-alpine3.17
            dockerfile: 1-amazoncorretto/alpine3.17/Dockerfile
            context: 1-amazoncorretto/alpine3.17
            version_arg: "19"
          - name: nginx
            version_tag: 1-bullseye
            dockerfile: 1-nginx/bullseye/Dockerfile
            context: 1-nginx/bullseye
            version_arg: "1"
          - name: node
            version_tag: 16-bullseye
            dockerfile: 1-node/bullseye/Dockerfile
            context: 1-node/bullseye
            version_arg: "16"
          - name: rust
            version_tag: 1.71.0-bullseye
            dockerfile: 1-rust/bullseye/Dockerfile
            context: 1-rust/bullseye
            version_arg: "1.71.0"
          - name: rust
            version_tag: bullseye
            dockerfile: 1-rust/bullseye/Dockerfile
            context: 1-rust/bullseye
            version_arg: stable
          - name: aws-cli
            version_tag: latest
            dockerfile: 1-aws-cli/al2/Dockerfile
            conetxt: 1-aws-cli/al2
            version_arg: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}
            naxgrp.jfrog.io/nax-platform-docker/${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}
          tags: |
            type=raw,value=${{ matrix.version_tag }}-{{date 'YYYYMMDD'}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ matrix.version_tag }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix=${{ matrix.version_tag }}-
            type=sha,prefix=${{ matrix.version_tag }}-,format=long
            type=schedule,pattern=${{ matrix.version_tag }}-{{date 'YYYYMMDD'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_RW }}
      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: naxgrp.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          build-args: |
            VERSION=${{ matrix.version_arg }}
            CACHE_BUST=${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.version_tag }}-buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.version_tag }}-buildcache,mode=max
      - name: Record Summary
        run: |
          echo "### Docker Tags" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
  app:
    needs:
      - base
      - lang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: cargo-chef
            version_tag: "0.1-bullseye"
            dockerfile: 2-cargo-chef/rust-bullseye/Dockerfile
            context: 2-cargo-chef/rust-bullseye
            version_arg: "^0.1" # version of cargo-chef
            image_tag_arg: "bullseye" # latest version of rust
            variants: "linux/amd64"
          - name: cloudfront-invalidator
            version_tag: "latest-aws-cli"
            dockerfile: 2-cloudfront-invalidator/aws-cli/Dockerfile
            context: 2-cloudfront-invalidator/aws-cli
            version_arg: "" # unused
            image_tag_arg: "latest"
            variants: "linux/amd64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}
            naxgrp.jfrog.io/nax-platform-docker/${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}
          tags: |
            type=raw,value=${{ matrix.version_tag }}-{{date 'YYYYMMDD'}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ matrix.version_tag }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix=${{ matrix.version_tag }}-
            type=sha,prefix=${{ matrix.version_tag }}-,format=long
            type=schedule,pattern=${{ matrix.version_tag }}-{{date 'YYYYMMDD'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_RW }}
      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: naxgrp.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          build-args: |
            VERSION=${{ matrix.version_arg }}
            IMAGE_TAG=${{ matrix.image_tag_arg }}
            CACHE_BUST=${{ github.run_id }}
          platforms: ${{ matrix.variants }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.version_tag }}-buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.version_tag }}-buildcache,mode=max
      - name: Record Summary
        run: |
          echo "### Docker Tags" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
